export const CHANGE_SETTINGS_INPUT = 'settings/CHANGE_SETTINGS_INPUT';
export const CHANGE_SETTINGS_INPUT_COMPANY = 'settings/CHANGE_SETTINGS_INPUT_COMPANY';
export const CHANGE_SOURCE_FUNDS = 'settings/CHANGE_SOURCE_FUNDS';
export const CHANGE_SETTINGS_INPUT_BENEFICIAL = 'settings/CHANGE_SETTINGS_INPUT_BENEFICIAL';
export const ADD_BENEFICIAL = 'settings/ADD_BENEFICIAL';
export const INCREMENT_BENEFICIAL_ID = 'settings/INCREMENT_BENEFICIAL_ID';
export const SET_SETTINGS_UPLOAD_PROGRESS = 'settings/SET_SETTINGS_UPLOAD_PROGRESS';