export const CHANGE_SETTINGS_INPUT = 'settings/CHANGE_SETTINGS_INPUT';
export const CHANGE_SETTINGS_INPUT_COMPANY = 'settings/CHANGE_SETTINGS_INPUT_COMPANY';
export const CHANGE_SOURCE_FUNDS = 'settings/CHANGE_SOURCE_FUNDS';
export const CHANGE_SETTINGS_INPUT_BENEFICIAL = 'settings/CHANGE_SETTINGS_INPUT_BENEFICIAL';
export const ADD_BENEFICIAL = 'settings/ADD_BENEFICIAL';
export const INCREMENT_BENEFICIAL_ID = 'settings/INCREMENT_BENEFICIAL_ID';
export const CHANGE_SETTINGS_DOCUMENT_INDIVIDUAL_USER = 'settings/CHANGE_SETTINGS_DOCUMENT_INDIVIDUAL_USER';
export const CHANGE_SETTINGS_DOCUMENT_ENTITY_USER = 'settings/CHANGE_SETTINGS_DOCUMENT_ENTITY_USER';
export const CHANGE_SETTINGS_DOCUMENT_ENTITY_COMPANY = 'settings/CHANGE_SETTINGS_DOCUMENT_ENTITY_COMPANY';
export const CHANGE_SETTINGS_DOCUMENT_ENTITY_BENEFICIAL = 'settings/CHANGE_SETTINGS_DOCUMENT_ENTITY_BENEFICIAL';
export const CHANGE_SETTINGS_MODAL = 'settings/CHANGE_SETTINGS_MODAL';
export const CHANGE_SETTINGS_ERROR = 'settings/CHANGE_SETTINGS_ERROR';
export const CHANGE_SETTINGS_SUCCESS = 'settings/CHANGE_SETTINGS_SUCCESS';

export const SETTINGS_INITIAL_USER_FILE = 'settings/SETTINGS_INITIAL_USER_FILE';
export const SETTINGS_INITIAL_USER_PROFILE = 'settings/SETTINGS_INITIAL_USER_PROFILE';
export const SETTINGS_INITIAL_USER_IMAGE = 'settings/SETTINGS_INITIAL_USER_IMAGE';

export const SETTINGS_INITIAL_COMPANY_USER_PROFILE = 'settings/SETTINGS_INITIAL_COMPANY_USER_PROFILE';
export const SETTINGS_INITIAL_COMPANY_USER_FILE = 'settings/SETTINGS_INITIAL_COMPANY_USER_FILE';
export const SETTINGS_INITIAL_COMPANY_PROFILE = 'settings/SETTINGS_INITIAL_COMPANY_PROFILE';
export const SETTINGS_INITIAL_COMPANY_FILE = 'settings/SETTINGS_INITIAL_COMPANY_FILE';
export const SETTINGS_INITIAL_BENEFICIAL = 'settings/SETTINGS_INITIAL_BENEFICIAL';
export const SETTINGS_INITIAL_BENEFICIAL_FILE = 'settings/SETTINGS_INITIAL_BENEFICIAL_FILE';