export const SIGNUP_CHANGE_EMAIL = 'SIGNUP_CHANGE_EMAIL';
export const SIGNUP_CHANGE_PASSWORD = 'SIGNUP_CHANGE_PASSWORD';
export const SIGNUP_CHANGE_REPEAT_PASSWORD = 'SIGNUP_CHANGE_REPEAT_PASSWORD';
export const SIGNUP_SET_SIGNUP_IN_PROGRESS = 'SIGNUP_SET_SIGNUP_IN_PROGRESS';
export const SIGNUP_SET_ERROR = 'SIGNUP_SET_ERROR';