export const LOGIN_CHANGE_EMAIL = 'LOGIN_CHANGE_EMAIL';
export const LOGIN_CHANGE_PASSWORD = 'LOGIN_CHANGE_PASSWORD';
export const LOGIN_SET_AUTH_IN_PROGRESS = 'LOGIN_SET_AUTH_IN_PROGRESS';
export const LOGIN_SET_ERROR = 'LOGIN_SET_ERROR';