export const ADD_USERS = 'admin/ADD_USERS';
export const ADD_APPLICATION = 'admin/ADD_APPLICATION';

export const SORTED_USERS = 'admin/SORTED_USERS';
export const SORTED_APPLICATIONS = 'admin/SORTED_APPLICATIONS';

export const CHANGE_DELETE_USERS = 'admin/CHANGE_DELETE_USERS';
export const CHANGE_DELETE_APPLICATIONS = 'admin/CHANGE_DELETE_APPLICATIONS';
export const CHANGE_USER_ROLE = 'admin/CHANGE_USER_ROLE';
export const CHANGE_APPLICATION_STATUS = 'admin/CHANGE_APPLICATION_STATUS';