export const ADD_USERS = 'admin/ADD_USERS';
export const ADD_APPLICATION = 'admin/ADD_APPLICATION';

export const SORTED_USERS = 'admin/SORTED_USERS';
export const SORTED_APPLICATIONS = 'admin/SORTED_APPLICATIONS';

export const CHANGE_DELETE_USERS = 'admin/CHANGE_DELETE_USERS';
export const CHANGE_DELETE_APPLICATIONS = 'admin/CHANGE_DELETE_APPLICATIONS';
export const CHANGE_USER_ROLE = 'admin/CHANGE_USER_ROLE';
export const CHANGE_APPLICATION_STATUS = 'admin/CHANGE_APPLICATION_STATUS';

export const SET_ADMIN_CURRENCY = 'admin/SET_ADMIN_CURRENCY';
export const SET_ADMIN_CURRENTCURRENCY = 'admin/SET_ADMIN_CURRENTCURRENCY';
export const SET_ADMIN_CURRENCY_VALUE = 'admin/SET_ADMIN_CURRENCY_VALUE';
export const SET_ADMIN_TOKEN_VALUE = 'admin/SET_ADMIN_TOKEN_VALUE';
export const SET_ADMIN_CURRENT_BONUS = 'admin/SET_ADMIN_CURRENT_BONUS';
export const SET_ADMIN_TRANSFER_DATA = 'admin/SET_ADMIN_TRANSFER_DATA';
